import json

ALLOWED_ACTIONS = [
    "create_parametric_block",
    "generate_spice_netlist"
]

REQUIRED_KEYS = ["action", "parameters"]

def validate_output(model_output):
    """
    Validates structured JSON output generated by the model.
    Ensures required schema keys and allowed actions.
    """
    try:
        data = json.loads(model_output)

        # Check required keys
        for key in REQUIRED_KEYS:
            if key not in data:
                return False, "Missing required key"

        # Check allowed actions
        if data["action"] not in ALLOWED_ACTIONS:
            return False, "Action not permitted"

        return True, "Valid output"

    except json.JSONDecodeError:
        return False, "Invalid JSON format"
